<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="33877" started-at="2020-10-12T16:16:25Z" finished-at="2020-10-12T16:16:59Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="33877" started-at="2020-10-12T16:16:25Z" finished-at="2020-10-12T16:16:59Z">
      <class name="testCases.Login_TestCase">
        <test-method status="PASS" signature="startReport()[pri:0, instance:testCases.Login_TestCase@1817d444]" name="startReport" is-config="true" duration-ms="106" started-at="2020-10-12T21:46:25Z" finished-at="2020-10-12T21:46:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startReport -->
        <test-method status="PASS" signature="initialization()[pri:0, instance:testCases.Login_TestCase@1817d444]" name="initialization" is-config="true" duration-ms="11415" started-at="2020-10-12T21:46:25Z" finished-at="2020-10-12T21:46:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialization -->
        <test-method status="PASS" signature="launchandVerifys()[pri:0, instance:testCases.Login_TestCase@1817d444]" name="launchandVerifys" duration-ms="2433" started-at="2020-10-12T21:46:37Z" finished-at="2020-10-12T21:46:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchandVerifys -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:testCases.Login_TestCase@1817d444]" name="getResult" is-config="true" duration-ms="2" started-at="2020-10-12T21:46:39Z" finished-at="2020-10-12T21:46:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=launchandVerifys status=SUCCESS method=Login_TestCase.launchandVerifys()[pri:0, instance:testCases.Login_TestCase@1817d444] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="FAIL" signature="validateLoginFunction()[pri:0, instance:testCases.Login_TestCase@1817d444]" name="validateLoginFunction" duration-ms="19694" started-at="2020-10-12T21:46:39Z" finished-at="2020-10-12T21:46:59Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
null
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:37)
	at root_base.Base_Root.Assertvalues(Base_Root.java:58)
	at pages.Login_page.LoginWithValidCredentials(Login_page.java:117)
	at testCases.Login_TestCase.validateLoginFunction(Login_TestCase.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateLoginFunction -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:testCases.Login_TestCase@1817d444]" name="getResult" is-config="true" duration-ms="2" started-at="2020-10-12T21:46:59Z" finished-at="2020-10-12T21:46:59Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=validateLoginFunction status=FAILURE method=Login_TestCase.validateLoginFunction()[pri:0, instance:testCases.Login_TestCase@1817d444] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testCases.Login_TestCase@1817d444]" name="tearDown" is-config="true" duration-ms="213" started-at="2020-10-12T21:46:59Z" finished-at="2020-10-12T21:46:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testCases.Login_TestCase -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
